/**
 * Daftar lengkap URL LPSE seluruh Indonesia
 * Format: { nama: string, url: string }
 * Semua URL mengikuti pola: https://spse.inaproc.id/{slug}/eproc4
 * atau domain LPSE mandiri masing-masing daerah
 *
 * Sumber: Portal INAPROC (spse.inaproc.id) & data publik LKPP
 */
const LPSE_LIST = [
  // ── KEMENTERIAN & LEMBAGA ──────────────────────────────────────────
  { nama: "LPSE Kementerian Keuangan", url: "https://spse.inaproc.id/kemenkeu" },
  { nama: "LPSE Kementerian PUPR", url: "https://spse.inaproc.id/pu" },
  { nama: "LPSE Kementerian Kesehatan", url: "https://spse.inaproc.id/depkes/eproc4" },
  { nama: "LPSE Kementerian Pendidikan", url: "https://spse.inaproc.id/kemdikbud/eproc4" },
  { nama: "LPSE Kementerian Pertanian", url: "https://spse.inaproc.id/deptan/eproc4" },
  { nama: "LPSE Kementerian Dalam Negeri", url: "https://spse.inaproc.id/depdagri/eproc4" },
  { nama: "LPSE Kementerian Lingkungan Hidup", url: "https://spse.inaproc.id/menlhk/eproc4" },
  { nama: "LPSE LKPP", url: "https://spse.inaproc.id/lkpp" },
  { nama: "LPSE BPKP", url: "https://spse.inaproc.id/bpkp" },
  { nama: "LPSE BPS", url: "https://spse.inaproc.id/bps" },
  { nama: "LPSE KPK", url: "https://spse.inaproc.id/kpk/eproc4" },
  { nama: "LPSE Mahkamah Agung", url: "https://spse.inaproc.id/mahkamahagung" },
  { nama: "LPSE Kejaksaan Agung", url: "https://spse.inaproc.id/kejaksaan" },
  { nama: "LPSE Polri", url: "https://spse.inaproc.id/polri" },
  { nama: "LPSE TNI AD", url: "https://spse.inaproc.id/tniad" },
  { nama: "LPSE Kementerian Kominfo", url: "https://spse.inaproc.id/kominfo/eproc4" },
  { nama: "LPSE Kementerian ESDM", url: "https://spse.inaproc.id/esdm" },
  { nama: "LPSE Kementerian Perindustrian", url: "https://spse.inaproc.id/kemenperin" },
  { nama: "LPSE Kementerian Perdagangan", url: "https://spse.inaproc.id/kemendag" },
  { nama: "LPSE Kementerian Tenaga Kerja", url: "https://spse.inaproc.id/kemenaker/eproc4" },
  { nama: "LPSE Kementerian Perhubungan", url: "https://spse.inaproc.id/dephub" },
  { nama: "LPSE Kementerian Kelautan", url: "https://spse.inaproc.id/kkp" },
  { nama: "LPSE Kementerian Pariwisata", url: "https://spse.inaproc.id/kemenpar" },
  { nama: "LPSE Kementerian Agama", url: "https://spse.inaproc.id/depag/eproc4" },
  { nama: "LPSE Kementerian Sosial", url: "https://spse.inaproc.id/depsos/eproc4" },
  { nama: "LPSE Kementerian PMK", url: "https://spse.inaproc.id/pmk/eproc4" },
  { nama: "LPSE BAPPENAS", url: "https://spse.inaproc.id/bappenas" },
  { nama: "LPSE BRIN", url: "https://spse.inaproc.id/brin" },

  // ── DKI JAKARTA ──────────────────────────────────────────────────────
  { nama: "LPSE Provinsi DKI Jakarta", url: "https://spse.inaproc.id/jakarta" },
  { nama: "LPSE Kota Jakarta Pusat", url: "https://spse.inaproc.id/jakpus/eproc4" },
  { nama: "LPSE Kota Jakarta Selatan", url: "https://spse.inaproc.id/jaksel/eproc4" },
  { nama: "LPSE Kota Jakarta Timur", url: "https://spse.inaproc.id/jaktim/eproc4" },
  { nama: "LPSE Kota Jakarta Barat", url: "https://spse.inaproc.id/jakbar/eproc4" },
  { nama: "LPSE Kota Jakarta Utara", url: "https://spse.inaproc.id/jakut/eproc4" },

  // ── JAWA BARAT ────────────────────────────────────────────────────────
  { nama: "LPSE Provinsi Jawa Barat", url: "https://spse.inaproc.id/jabarprov" },
  { nama: "LPSE Kota Bandung", url: "https://spse.inaproc.id/bandung" },
  { nama: "LPSE Kota Bogor", url: "https://spse.inaproc.id/kotabogor" },
  { nama: "LPSE Kota Bekasi", url: "https://spse.inaproc.id/bekasikota" },
  { nama: "LPSE Kota Depok", url: "https://spse.inaproc.id/depokkota/eproc4" },
  { nama: "LPSE Kota Cimahi", url: "https://spse.inaproc.id/cimahikota" },
  { nama: "LPSE Kota Sukabumi", url: "https://spse.inaproc.id/sukabumikota/eproc4" },
  { nama: "LPSE Kota Cirebon", url: "https://spse.inaproc.id/cirebonkota/eproc4" },
  { nama: "LPSE Kota Tasikmalaya", url: "https://spse.inaproc.id/tasikmalayakota" },
  { nama: "LPSE Kota Banjar", url: "https://spse.inaproc.id/banjar/eproc4" },
  { nama: "LPSE Kabupaten Bogor", url: "https://spse.inaproc.id/bogorkab" },
  { nama: "LPSE Kabupaten Bekasi", url: "https://spse.inaproc.id/bekasikab" },
  { nama: "LPSE Kabupaten Karawang", url: "https://spse.inaproc.id/karawang/eproc4" },
  { nama: "LPSE Kabupaten Purwakarta", url: "https://spse.inaproc.id/purwakarta/eproc4" },
  { nama: "LPSE Kabupaten Subang", url: "https://spse.inaproc.id/subang" },
  { nama: "LPSE Kabupaten Indramayu", url: "https://spse.inaproc.id/indramayu/eproc4" },
  { nama: "LPSE Kabupaten Cirebon", url: "https://spse.inaproc.id/cirebonkab" },
  { nama: "LPSE Kabupaten Majalengka", url: "https://spse.inaproc.id/majalengka/eproc4" },
  { nama: "LPSE Kabupaten Kuningan", url: "https://spse.inaproc.id/kuningan/eproc4" },
  { nama: "LPSE Kabupaten Sumedang", url: "https://spse.inaproc.id/sumedang/eproc4" },
  { nama: "LPSE Kabupaten Garut", url: "https://spse.inaproc.id/garut/eproc4" },
  { nama: "LPSE Kabupaten Bandung", url: "https://spse.inaproc.id/bandungkab" },
  { nama: "LPSE Kabupaten Bandung Barat", url: "https://spse.inaproc.id/bandungbarat/eproc4" },
  { nama: "LPSE Kabupaten Sukabumi", url: "https://spse.inaproc.id/sukabumikab" },
  { nama: "LPSE Kabupaten Cianjur", url: "https://spse.inaproc.id/cianjur/eproc4" },
  { nama: "LPSE Kabupaten Tasikmalaya", url: "https://spse.inaproc.id/tasikmalayakab" },
  { nama: "LPSE Kabupaten Ciamis", url: "https://spse.inaproc.id/ciamis/eproc4" },
  { nama: "LPSE Kabupaten Pangandaran", url: "https://spse.inaproc.id/pangandaran/eproc4" },

  // ── BANTEN ────────────────────────────────────────────────────────────
  { nama: "LPSE Provinsi Banten", url: "https://spse.inaproc.id/banten/eproc4" },
  { nama: "LPSE Kota Tangerang", url: "https://spse.inaproc.id/tangerangkota" },
  { nama: "LPSE Kota Tangerang Selatan", url: "https://spse.inaproc.id/tangerangselatankota" },
  { nama: "LPSE Kota Serang", url: "https://spse.inaproc.id/serangkota" },
  { nama: "LPSE Kota Cilegon", url: "https://spse.inaproc.id/cilegon" },
  { nama: "LPSE Kabupaten Tangerang", url: "https://spse.inaproc.id/tangerangkab" },
  { nama: "LPSE Kabupaten Serang", url: "https://spse.inaproc.id/serangkab" },
  { nama: "LPSE Kabupaten Lebak", url: "https://spse.inaproc.id/lebak/eproc4" },
  { nama: "LPSE Kabupaten Pandeglang", url: "https://spse.inaproc.id/pandeglang/eproc4" },

  // ── JAWA TENGAH ───────────────────────────────────────────────────────
  { nama: "LPSE Provinsi Jawa Tengah", url: "https://spse.inaproc.id/jatengprov" },
  { nama: "LPSE Kota Semarang", url: "https://spse.inaproc.id/semarangkota" },
  { nama: "LPSE Kota Solo", url: "https://spse.inaproc.id/surakarta" },
  { nama: "LPSE Kota Magelang", url: "https://spse.inaproc.id/magelangkota" },
  { nama: "LPSE Kota Salatiga", url: "https://spse.inaproc.id/salatiga" },
  { nama: "LPSE Kota Pekalongan", url: "https://spse.inaproc.id/pekalongan/eproc4" },
  { nama: "LPSE Kota Tegal", url: "https://spse.inaproc.id/tegalkota" },
  { nama: "LPSE Kabupaten Semarang", url: "https://spse.inaproc.id/semarangkab" },
  { nama: "LPSE Kabupaten Demak", url: "https://spse.inaproc.id/demak/eproc4" },
  { nama: "LPSE Kabupaten Kendal", url: "https://spse.inaproc.id/kendal/eproc4" },
  { nama: "LPSE Kabupaten Batang", url: "https://spse.inaproc.id/batang/eproc4" },
  { nama: "LPSE Kabupaten Pekalongan", url: "https://spse.inaproc.id/pekalongan/eproc4" },
  { nama: "LPSE Kabupaten Pemalang", url: "https://spse.inaproc.id/pemalang/eproc4" },
  { nama: "LPSE Kabupaten Tegal", url: "https://spse.inaproc.id/tegalkab" },
  { nama: "LPSE Kabupaten Brebes", url: "https://spse.inaproc.id/brebes/eproc4" },
  { nama: "LPSE Kabupaten Banyumas", url: "https://spse.inaproc.id/banyumas/eproc4" },
  { nama: "LPSE Kabupaten Cilacap", url: "https://spse.inaproc.id/cilacap/eproc4" },
  { nama: "LPSE Kabupaten Kebumen", url: "https://spse.inaproc.id/kebumen/eproc4" },
  { nama: "LPSE Kabupaten Purworejo", url: "https://spse.inaproc.id/purworejo/eproc4" },
  { nama: "LPSE Kabupaten Magelang", url: "https://spse.inaproc.id/magelangkab" },
  { nama: "LPSE Kabupaten Wonosobo", url: "https://spse.inaproc.id/wonosobo/eproc4" },
  { nama: "LPSE Kabupaten Temanggung", url: "https://spse.inaproc.id/temanggung/eproc4" },
  { nama: "LPSE Kabupaten Boyolali", url: "https://spse.inaproc.id/boyolali" },
  { nama: "LPSE Kabupaten Klaten", url: "https://spse.inaproc.id/klaten" },
  { nama: "LPSE Kabupaten Sukoharjo", url: "https://spse.inaproc.id/sukoharjo/eproc4" },
  { nama: "LPSE Kabupaten Wonogiri", url: "https://spse.inaproc.id/wonogiri/eproc4" },
  { nama: "LPSE Kabupaten Karanganyar", url: "https://spse.inaproc.id/karanganyar/eproc4" },
  { nama: "LPSE Kabupaten Sragen", url: "https://spse.inaproc.id/sragen/eproc4" },
  { nama: "LPSE Kabupaten Grobogan", url: "https://spse.inaproc.id/grobogan" },
  { nama: "LPSE Kabupaten Blora", url: "https://spse.inaproc.id/blora/eproc4" },
  { nama: "LPSE Kabupaten Rembang", url: "https://spse.inaproc.id/rembang/eproc4" },
  { nama: "LPSE Kabupaten Pati", url: "https://spse.inaproc.id/pati/eproc4" },
  { nama: "LPSE Kabupaten Kudus", url: "https://spse.inaproc.id/kudus/eproc4" },
  { nama: "LPSE Kabupaten Jepara", url: "https://spse.inaproc.id/jepara" },
  { nama: "LPSE Kabupaten Purbalingga", url: "https://spse.inaproc.id/purbalingga/eproc4" },
  { nama: "LPSE Kabupaten Banjarnegara", url: "https://spse.inaproc.id/banjarnegara/eproc4" },

  // ── DI YOGYAKARTA ─────────────────────────────────────────────────────
  { nama: "LPSE Provinsi DIY", url: "https://spse.inaproc.id/diy/eproc4" },
  { nama: "LPSE Kota Yogyakarta", url: "https://spse.inaproc.id/yogyakarta/eproc4" },
  { nama: "LPSE Kabupaten Sleman", url: "https://spse.inaproc.id/sleman/eproc4" },
  { nama: "LPSE Kabupaten Bantul", url: "https://spse.inaproc.id/bantul/eproc4" },
  { nama: "LPSE Kabupaten Kulonprogo", url: "https://spse.inaproc.id/kulonprogo/eproc4" },
  { nama: "LPSE Kabupaten Gunungkidul", url: "https://spse.inaproc.id/gunungkidul/eproc4" },

  // ── JAWA TIMUR ────────────────────────────────────────────────────────
  { nama: "LPSE Provinsi Jawa Timur", url: "https://spse.inaproc.id/jatim/eproc4" },
  { nama: "LPSE Kota Surabaya", url: "https://spse.inaproc.id/surabaya" },
  { nama: "LPSE Kota Malang", url: "https://spse.inaproc.id/malangkota" },
  { nama: "LPSE Kota Mojokerto", url: "https://spse.inaproc.id/mojokertokota" },
  { nama: "LPSE Kota Kediri", url: "https://spse.inaproc.id/kedirikota" },
  { nama: "LPSE Kota Blitar", url: "https://spse.inaproc.id/blitarkota" },
  { nama: "LPSE Kota Madiun", url: "https://spse.inaproc.id/madiunkota" },
  { nama: "LPSE Kota Pasuruan", url: "https://spse.inaproc.id/pasuruankota" },
  { nama: "LPSE Kota Probolinggo", url: "https://spse.inaproc.id/probolinggokota" },
  { nama: "LPSE Kota Batu", url: "https://spse.inaproc.id/batu/eproc4" },
  { nama: "LPSE Kabupaten Sidoarjo", url: "https://spse.inaproc.id/sidoarjo/eproc4" },
  { nama: "LPSE Kabupaten Gresik", url: "https://spse.inaproc.id/gresik/eproc4" },
  { nama: "LPSE Kabupaten Mojokerto", url: "https://spse.inaproc.id/mojokertokab" },
  { nama: "LPSE Kabupaten Jombang", url: "https://spse.inaproc.id/jombang/eproc4" },
  { nama: "LPSE Kabupaten Malang", url: "https://spse.inaproc.id/malangkab" },
  { nama: "LPSE Kabupaten Pasuruan", url: "https://spse.inaproc.id/pasuruankab" },
  { nama: "LPSE Kabupaten Probolinggo", url: "https://spse.inaproc.id/probolinggokab" },
  { nama: "LPSE Kabupaten Lumajang", url: "https://spse.inaproc.id/lumajang/eproc4" },
  { nama: "LPSE Kabupaten Jember", url: "https://spse.inaproc.id/jember/eproc4" },
  { nama: "LPSE Kabupaten Banyuwangi", url: "https://spse.inaproc.id/banyuwangi/eproc4" },
  { nama: "LPSE Kabupaten Situbondo", url: "https://spse.inaproc.id/situbondo/eproc4" },
  { nama: "LPSE Kabupaten Bondowoso", url: "https://spse.inaproc.id/bondowoso/eproc4" },
  { nama: "LPSE Kabupaten Kediri", url: "https://spse.inaproc.id/kedirikab" },
  { nama: "LPSE Kabupaten Blitar", url: "https://spse.inaproc.id/blitarkab" },
  { nama: "LPSE Kabupaten Tulungagung", url: "https://spse.inaproc.id/tulungagung" },
  { nama: "LPSE Kabupaten Trenggalek", url: "https://spse.inaproc.id/trenggalek/eproc4" },
  { nama: "LPSE Kabupaten Nganjuk", url: "https://spse.inaproc.id/nganjuk/eproc4" },
  { nama: "LPSE Kabupaten Madiun", url: "https://spse.inaproc.id/madiunkab" },
  { nama: "LPSE Kabupaten Magetan", url: "https://spse.inaproc.id/magetan" },
  { nama: "LPSE Kabupaten Ngawi", url: "https://spse.inaproc.id/ngawi/eproc4" },
  { nama: "LPSE Kabupaten Ponorogo", url: "https://spse.inaproc.id/ponorogo" },
  { nama: "LPSE Kabupaten Pacitan", url: "https://spse.inaproc.id/pacitan/eproc4" },
  { nama: "LPSE Kabupaten Lamongan", url: "https://spse.inaproc.id/lamongan/eproc4" },
  { nama: "LPSE Kabupaten Bojonegoro", url: "https://spse.inaproc.id/bojonegoro/eproc4" },
  { nama: "LPSE Kabupaten Tuban", url: "https://spse.inaproc.id/tuban/eproc4" },
  { nama: "LPSE Kabupaten Bangkalan", url: "https://spse.inaproc.id/bangkalan/eproc4" },
  { nama: "LPSE Kabupaten Sampang", url: "https://spse.inaproc.id/sampang/eproc4" },
  { nama: "LPSE Kabupaten Pamekasan", url: "https://spse.inaproc.id/pamekasan/eproc4" },
  { nama: "LPSE Kabupaten Sumenep", url: "https://spse.inaproc.id/sumenep/eproc4" },

  // ── SUMATERA UTARA ────────────────────────────────────────────────────
  { nama: "LPSE Provinsi Sumatera Utara", url: "https://spse.inaproc.id/sumutprov" },
  { nama: "LPSE Kota Medan", url: "https://spse.inaproc.id/medan/eproc4" },
  { nama: "LPSE Kota Binjai", url: "https://spse.inaproc.id/binjai/eproc4" },
  { nama: "LPSE Kota Tebing Tinggi", url: "https://spse.inaproc.id/tebingtinggi/eproc4" },
  { nama: "LPSE Kota Pematangsiantar", url: "https://spse.inaproc.id/pematangsiantar" },
  { nama: "LPSE Kota Sibolga", url: "https://spse.inaproc.id/sibolga/eproc4" },
  { nama: "LPSE Kota Padangsidimpuan", url: "https://spse.inaproc.id/padangsidimpuan/eproc4" },
  { nama: "LPSE Kota Tanjungbalai", url: "https://spse.inaproc.id/tanjungbalai/eproc4" },
  { nama: "LPSE Kota Gunungsitoli", url: "https://spse.inaproc.id/gunungsitoli/eproc4" },
  { nama: "LPSE Kabupaten Deli Serdang", url: "https://spse.inaproc.id/deliserdang/eproc4" },
  { nama: "LPSE Kabupaten Langkat", url: "https://spse.inaproc.id/langkat/eproc4" },
  { nama: "LPSE Kabupaten Karo", url: "https://spse.inaproc.id/karo/eproc4" },
  { nama: "LPSE Kabupaten Simalungun", url: "https://spse.inaproc.id/simalungun/eproc4" },
  { nama: "LPSE Kabupaten Asahan", url: "https://spse.inaproc.id/asahan/eproc4" },
  { nama: "LPSE Kabupaten Labuhanbatu", url: "https://spse.inaproc.id/labuhanbatu/eproc4" },
  { nama: "LPSE Kabupaten Tapanuli Utara", url: "https://spse.inaproc.id/tapanut/eproc4" },
  { nama: "LPSE Kabupaten Tapanuli Tengah", url: "https://spse.inaproc.id/tapantengah/eproc4" },
  { nama: "LPSE Kabupaten Tapanuli Selatan", url: "https://spse.inaproc.id/tapansel/eproc4" },
  { nama: "LPSE Kabupaten Nias", url: "https://spse.inaproc.id/nias/eproc4" },
  { nama: "LPSE Kabupaten Mandailing Natal", url: "https://spse.inaproc.id/madina" },
  { nama: "LPSE Kabupaten Batubara", url: "https://spse.inaproc.id/batubara/eproc4" },
  { nama: "LPSE Kabupaten Padang Lawas", url: "https://spse.inaproc.id/padanglawas/eproc4" },

  // ── SUMATERA BARAT ────────────────────────────────────────────────────
  { nama: "LPSE Provinsi Sumatera Barat", url: "https://spse.inaproc.id/sumbarprov" },
  { nama: "LPSE Kota Padang", url: "https://spse.inaproc.id/padang" },
  { nama: "LPSE Kota Bukittinggi", url: "https://spse.inaproc.id/bukittinggi/eproc4" },
  { nama: "LPSE Kota Solok", url: "https://spse.inaproc.id/solokkota" },
  { nama: "LPSE Kota Padangpanjang", url: "https://spse.inaproc.id/padangpanjang" },
  { nama: "LPSE Kota Payakumbuh", url: "https://spse.inaproc.id/payakumbuh/eproc4" },
  { nama: "LPSE Kota Sawahlunto", url: "https://spse.inaproc.id/sawahlunto/eproc4" },
  { nama: "LPSE Kota Pariaman", url: "https://spse.inaproc.id/pariaman/eproc4" },
  { nama: "LPSE Kabupaten Agam", url: "https://spse.inaproc.id/agam/eproc4" },
  { nama: "LPSE Kabupaten Limapuluh Kota", url: "https://spse.inaproc.id/limapuluhkota/eproc4" },
  { nama: "LPSE Kabupaten Pesisir Selatan", url: "https://spse.inaproc.id/pesisirselatan/eproc4" },
  { nama: "LPSE Kabupaten Solok", url: "https://spse.inaproc.id/solokkab" },
  { nama: "LPSE Kabupaten Sijunjung", url: "https://spse.inaproc.id/sijunjung" },
  { nama: "LPSE Kabupaten Tanah Datar", url: "https://spse.inaproc.id/tanahdatar" },
  { nama: "LPSE Kabupaten Padang Pariaman", url: "https://spse.inaproc.id/padangpariaman/eproc4" },
  { nama: "LPSE Kabupaten Pasaman", url: "https://spse.inaproc.id/pasaman/eproc4" },

  // ── RIAU ─────────────────────────────────────────────────────────────
  { nama: "LPSE Provinsi Riau", url: "https://spse.inaproc.id/riauprov/eproc4" },
  { nama: "LPSE Kota Pekanbaru", url: "https://spse.inaproc.id/pekanbaru" },
  { nama: "LPSE Kota Dumai", url: "https://spse.inaproc.id/dumai/eproc4" },
  { nama: "LPSE Kabupaten Kampar", url: "https://spse.inaproc.id/kampar/eproc4" },
  { nama: "LPSE Kabupaten Rokan Hulu", url: "https://spse.inaproc.id/rokanhulu/eproc4" },
  { nama: "LPSE Kabupaten Rokan Hilir", url: "https://spse.inaproc.id/rokanhilir/eproc4" },
  { nama: "LPSE Kabupaten Bengkalis", url: "https://spse.inaproc.id/bengkalis/eproc4" },
  { nama: "LPSE Kabupaten Siak", url: "https://spse.inaproc.id/siak/eproc4" },
  { nama: "LPSE Kabupaten Pelalawan", url: "https://spse.inaproc.id/pelalawan/eproc4" },
  { nama: "LPSE Kabupaten Indragiri Hulu", url: "https://spse.inaproc.id/inhil/eproc4" },
  { nama: "LPSE Kabupaten Indragiri Hilir", url: "https://spse.inaproc.id/inhul/eproc4" },
  { nama: "LPSE Kabupaten Kuantan Singingi", url: "https://spse.inaproc.id/kuansing" },

  // ── KEPULAUAN RIAU ────────────────────────────────────────────────────
  { nama: "LPSE Provinsi Kepri", url: "https://spse.inaproc.id/kepriprov" },
  { nama: "LPSE Kota Batam", url: "https://spse.inaproc.id/batam" },
  { nama: "LPSE Kota Tanjungpinang", url: "https://spse.inaproc.id/tanjungpinang/eproc4" },
  { nama: "LPSE Kabupaten Bintan", url: "https://spse.inaproc.id/bintan/eproc4" },
  { nama: "LPSE Kabupaten Karimun", url: "https://spse.inaproc.id/karimun/eproc4" },
  { nama: "LPSE Kabupaten Natuna", url: "https://spse.inaproc.id/natuna/eproc4" },
  { nama: "LPSE Kabupaten Lingga", url: "https://spse.inaproc.id/lingga/eproc4" },

  // ── SUMATERA SELATAN ──────────────────────────────────────────────────
  { nama: "LPSE Provinsi Sumatera Selatan", url: "https://spse.inaproc.id/sumprovsel/eproc4" },
  { nama: "LPSE Kota Palembang", url: "https://spse.inaproc.id/palembang" },
  { nama: "LPSE Kota Prabumulih", url: "https://spse.inaproc.id/prabumulih/eproc4" },
  { nama: "LPSE Kota Lubuklinggau", url: "https://spse.inaproc.id/lubuklinggau/eproc4" },
  { nama: "LPSE Kota Pagaralam", url: "https://spse.inaproc.id/pagaralam/eproc4" },
  { nama: "LPSE Kabupaten Ogan Ilir", url: "https://spse.inaproc.id/oganilir/eproc4" },
  { nama: "LPSE Kabupaten Ogan Komering Ilir", url: "https://spse.inaproc.id/oki/eproc4" },
  { nama: "LPSE Kabupaten Musi Banyuasin", url: "https://spse.inaproc.id/muba/eproc4" },
  { nama: "LPSE Kabupaten Banyuasin", url: "https://spse.inaproc.id/banyuasin/eproc4" },
  { nama: "LPSE Kabupaten Muara Enim", url: "https://spse.inaproc.id/muaraenim/eproc4" },
  { nama: "LPSE Kabupaten Lahat", url: "https://spse.inaproc.id/lahat/eproc4" },

  // ── LAMPUNG ───────────────────────────────────────────────────────────
  { nama: "LPSE Provinsi Lampung", url: "https://spse.inaproc.id/lampungprov" },
  { nama: "LPSE Kota Bandar Lampung", url: "https://spse.inaproc.id/bandarlampung/eproc4" },
  { nama: "LPSE Kota Metro", url: "https://spse.inaproc.id/metro/eproc4" },
  { nama: "LPSE Kabupaten Lampung Selatan", url: "https://spse.inaproc.id/lamsel/eproc4" },
  { nama: "LPSE Kabupaten Lampung Tengah", url: "https://spse.inaproc.id/lamteng/eproc4" },
  { nama: "LPSE Kabupaten Lampung Utara", url: "https://spse.inaproc.id/lampungutara/eproc4" },
  { nama: "LPSE Kabupaten Lampung Barat", url: "https://spse.inaproc.id/lampungbarat/eproc4" },
  { nama: "LPSE Kabupaten Tanggamus", url: "https://spse.inaproc.id/tanggamus" },
  { nama: "LPSE Kabupaten Way Kanan", url: "https://spse.inaproc.id/waykanan/eproc4" },
  { nama: "LPSE Kabupaten Tulang Bawang", url: "https://spse.inaproc.id/tulangbawang/eproc4" },
  { nama: "LPSE Kabupaten Pringsewu", url: "https://spse.inaproc.id/pringsewu/eproc4" },
  { nama: "LPSE Kabupaten Mesuji", url: "https://spse.inaproc.id/mesuji/eproc4" },
  { nama: "LPSE Kabupaten Pesawaran", url: "https://spse.inaproc.id/pesawaran/eproc4" },

  // ── BENGKULU ──────────────────────────────────────────────────────────
  { nama: "LPSE Provinsi Bengkulu", url: "https://spse.inaproc.id/bengkuluprov" },
  { nama: "LPSE Kota Bengkulu", url: "https://spse.inaproc.id/bengkulukota" },
  { nama: "LPSE Kabupaten Rejang Lebong", url: "https://spse.inaproc.id/rejanglebong/eproc4" },
  { nama: "LPSE Kabupaten Bengkulu Utara", url: "https://spse.inaproc.id/bengkuluutara/eproc4" },
  { nama: "LPSE Kabupaten Kepahiang", url: "https://spse.inaproc.id/kepahiang/eproc4" },
  { nama: "LPSE Kabupaten Mukomuko", url: "https://spse.inaproc.id/mukomuko/eproc4" },

  // ── JAMBI ─────────────────────────────────────────────────────────────
  { nama: "LPSE Provinsi Jambi", url: "https://spse.inaproc.id/jambiprov/eproc4" },
  { nama: "LPSE Kota Jambi", url: "https://spse.inaproc.id/jambikota/eproc4" },
  { nama: "LPSE Kota Sungai Penuh", url: "https://spse.inaproc.id/sungaipenuh/eproc4" },
  { nama: "LPSE Kabupaten Batanghari", url: "https://spse.inaproc.id/batanghari/eproc4" },
  { nama: "LPSE Kabupaten Muaro Jambi", url: "https://spse.inaproc.id/muarojambi/eproc4" },
  { nama: "LPSE Kabupaten Bungo", url: "https://spse.inaproc.id/bungo/eproc4" },
  { nama: "LPSE Kabupaten Tebo", url: "https://spse.inaproc.id/tebo/eproc4" },
  { nama: "LPSE Kabupaten Merangin", url: "https://spse.inaproc.id/merangin/eproc4" },
  { nama: "LPSE Kabupaten Sarolangun", url: "https://spse.inaproc.id/sarolangun/eproc4" },
  { nama: "LPSE Kabupaten Kerinci", url: "https://spse.inaproc.id/kerinci/eproc4" },

  // ── BANGKA BELITUNG ───────────────────────────────────────────────────
  { nama: "LPSE Provinsi Bangka Belitung", url: "https://spse.inaproc.id/babelprov/eproc4" },
  { nama: "LPSE Kota Pangkalpinang", url: "https://spse.inaproc.id/pangkalpinang/eproc4" },
  { nama: "LPSE Kabupaten Bangka", url: "https://spse.inaproc.id/bangka/eproc4" },
  { nama: "LPSE Kabupaten Belitung", url: "https://spse.inaproc.id/belitung/eproc4" },
  { nama: "LPSE Kabupaten Bangka Barat", url: "https://spse.inaproc.id/bangkabarat/eproc4" },
  { nama: "LPSE Kabupaten Bangka Tengah", url: "https://spse.inaproc.id/bangkatengah/eproc4" },

  // ── KALIMANTAN BARAT ──────────────────────────────────────────────────
  { nama: "LPSE Provinsi Kalimantan Barat", url: "https://spse.inaproc.id/kalbarprov/eproc4" },
  { nama: "LPSE Kota Pontianak", url: "https://spse.inaproc.id/pontianak/eproc4" },
  { nama: "LPSE Kota Singkawang", url: "https://spse.inaproc.id/singkawang/eproc4" },
  { nama: "LPSE Kabupaten Sambas", url: "https://spse.inaproc.id/sambas/eproc4" },
  { nama: "LPSE Kabupaten Mempawah", url: "https://spse.inaproc.id/mempawah/eproc4" },
  { nama: "LPSE Kabupaten Bengkayang", url: "https://spse.inaproc.id/bengkayang/eproc4" },
  { nama: "LPSE Kabupaten Landak", url: "https://spse.inaproc.id/landak/eproc4" },
  { nama: "LPSE Kabupaten Sanggau", url: "https://spse.inaproc.id/sanggau/eproc4" },
  { nama: "LPSE Kabupaten Sekadau", url: "https://spse.inaproc.id/sekadau/eproc4" },
  { nama: "LPSE Kabupaten Sintang", url: "https://spse.inaproc.id/sintang/eproc4" },
  { nama: "LPSE Kabupaten Melawi", url: "https://spse.inaproc.id/melawi/eproc4" },
  { nama: "LPSE Kabupaten Kapuas Hulu", url: "https://spse.inaproc.id/kapuashulu/eproc4" },
  { nama: "LPSE Kabupaten Ketapang", url: "https://spse.inaproc.id/ketapang/eproc4" },

  // ── KALIMANTAN TENGAH ─────────────────────────────────────────────────
  { nama: "LPSE Provinsi Kalimantan Tengah", url: "https://spse.inaproc.id/kaltengprov/eproc4" },
  { nama: "LPSE Kota Palangka Raya", url: "https://spse.inaproc.id/palangkaraya/eproc4" },
  { nama: "LPSE Kabupaten Kotawaringin Barat", url: "https://spse.inaproc.id/kotawaribar/eproc4" },
  { nama: "LPSE Kabupaten Kotawaringin Timur", url: "https://spse.inaproc.id/kotawaritim/eproc4" },
  { nama: "LPSE Kabupaten Barito Utara", url: "https://spse.inaproc.id/baritoutara/eproc4" },
  { nama: "LPSE Kabupaten Barito Selatan", url: "https://spse.inaproc.id/baritosel/eproc4" },
  { nama: "LPSE Kabupaten Kapuas", url: "https://spse.inaproc.id/kapuaskalteng/eproc4" },
  { nama: "LPSE Kabupaten Pulang Pisau", url: "https://spse.inaproc.id/pulangpisau/eproc4" },
  { nama: "LPSE Kabupaten Katingan", url: "https://spse.inaproc.id/katingan/eproc4" },

  // ── KALIMANTAN SELATAN ────────────────────────────────────────────────
  { nama: "LPSE Provinsi Kalimantan Selatan", url: "https://spse.inaproc.id/kalselprov/eproc4" },
  { nama: "LPSE Kota Banjarmasin", url: "https://spse.inaproc.id/banjarmasin/eproc4" },
  { nama: "LPSE Kota Banjarbaru", url: "https://spse.inaproc.id/banjarbaru/eproc4" },
  { nama: "LPSE Kabupaten Banjar", url: "https://spse.inaproc.id/banjarkab/eproc4" },
  { nama: "LPSE Kabupaten Tanah Laut", url: "https://spse.inaproc.id/tanalaut/eproc4" },
  { nama: "LPSE Kabupaten Kotabaru", url: "https://spse.inaproc.id/kotabaru/eproc4" },
  { nama: "LPSE Kabupaten Tapin", url: "https://spse.inaproc.id/tapin/eproc4" },
  { nama: "LPSE Kabupaten Hulu Sungai Selatan", url: "https://spse.inaproc.id/hss/eproc4" },
  { nama: "LPSE Kabupaten Hulu Sungai Tengah", url: "https://spse.inaproc.id/hst/eproc4" },
  { nama: "LPSE Kabupaten Hulu Sungai Utara", url: "https://spse.inaproc.id/hsu/eproc4" },
  { nama: "LPSE Kabupaten Balangan", url: "https://spse.inaproc.id/balangan/eproc4" },
  { nama: "LPSE Kabupaten Tabalong", url: "https://spse.inaproc.id/tabalong/eproc4" },
  { nama: "LPSE Kabupaten Barito Kuala", url: "https://spse.inaproc.id/batola/eproc4" },
  { nama: "LPSE Kabupaten Tanah Bumbu", url: "https://spse.inaproc.id/tanahumbu/eproc4" },

  // ── KALIMANTAN TIMUR ──────────────────────────────────────────────────
  { nama: "LPSE Provinsi Kalimantan Timur", url: "https://spse.inaproc.id/kaltimprov/eproc4" },
  { nama: "LPSE Kota Samarinda", url: "https://spse.inaproc.id/samarinda/eproc4" },
  { nama: "LPSE Kota Balikpapan", url: "https://spse.inaproc.id/balikpapan/eproc4" },
  { nama: "LPSE Kota Bontang", url: "https://spse.inaproc.id/bontang/eproc4" },
  { nama: "LPSE Kabupaten Kutai Kartanegara", url: "https://spse.inaproc.id/kukar/eproc4" },
  { nama: "LPSE Kabupaten Kutai Timur", url: "https://spse.inaproc.id/kutim/eproc4" },
  { nama: "LPSE Kabupaten Kutai Barat", url: "https://spse.inaproc.id/kubar/eproc4" },
  { nama: "LPSE Kabupaten Paser", url: "https://spse.inaproc.id/paser/eproc4" },
  { nama: "LPSE Kabupaten Penajam Paser Utara", url: "https://spse.inaproc.id/ppu/eproc4" },
  { nama: "LPSE Kabupaten Berau", url: "https://spse.inaproc.id/berau/eproc4" },

  // ── KALIMANTAN UTARA ──────────────────────────────────────────────────
  { nama: "LPSE Provinsi Kalimantan Utara", url: "https://spse.inaproc.id/kaltaraprov/eproc4" },
  { nama: "LPSE Kota Tarakan", url: "https://spse.inaproc.id/tarakan/eproc4" },
  { nama: "LPSE Kabupaten Bulungan", url: "https://spse.inaproc.id/bulungan/eproc4" },
  { nama: "LPSE Kabupaten Nunukan", url: "https://spse.inaproc.id/nunukan/eproc4" },
  { nama: "LPSE Kabupaten Malinau", url: "https://spse.inaproc.id/malinau/eproc4" },

  // ── SULAWESI SELATAN ──────────────────────────────────────────────────
  { nama: "LPSE Provinsi Sulawesi Selatan", url: "https://spse.inaproc.id/sulsel/eproc4" },
  { nama: "LPSE Kota Makassar", url: "https://spse.inaproc.id/makassar/eproc4" },
  { nama: "LPSE Kota Parepare", url: "https://spse.inaproc.id/parepare/eproc4" },
  { nama: "LPSE Kota Palopo", url: "https://spse.inaproc.id/palopo/eproc4" },
  { nama: "LPSE Kabupaten Gowa", url: "https://spse.inaproc.id/gowa/eproc4" },
  { nama: "LPSE Kabupaten Maros", url: "https://spse.inaproc.id/maros/eproc4" },
  { nama: "LPSE Kabupaten Pangkajene Kepulauan", url: "https://spse.inaproc.id/pangkep/eproc4" },
  { nama: "LPSE Kabupaten Barru", url: "https://spse.inaproc.id/barru/eproc4" },
  { nama: "LPSE Kabupaten Bone", url: "https://spse.inaproc.id/bone/eproc4" },
  { nama: "LPSE Kabupaten Sinjai", url: "https://spse.inaproc.id/sinjai/eproc4" },
  { nama: "LPSE Kabupaten Bulukumba", url: "https://spse.inaproc.id/bulukumba/eproc4" },
  { nama: "LPSE Kabupaten Bantaeng", url: "https://spse.inaproc.id/bantaeng/eproc4" },
  { nama: "LPSE Kabupaten Jeneponto", url: "https://spse.inaproc.id/jeneponto/eproc4" },
  { nama: "LPSE Kabupaten Takalar", url: "https://spse.inaproc.id/takalar/eproc4" },
  { nama: "LPSE Kabupaten Selayar", url: "https://spse.inaproc.id/selayar/eproc4" },
  { nama: "LPSE Kabupaten Wajo", url: "https://spse.inaproc.id/wajo/eproc4" },
  { nama: "LPSE Kabupaten Soppeng", url: "https://spse.inaproc.id/soppeng/eproc4" },
  { nama: "LPSE Kabupaten Sidrap", url: "https://spse.inaproc.id/sidrap/eproc4" },
  { nama: "LPSE Kabupaten Pinrang", url: "https://spse.inaproc.id/pinrang/eproc4" },
  { nama: "LPSE Kabupaten Enrekang", url: "https://spse.inaproc.id/enrekang/eproc4" },
  { nama: "LPSE Kabupaten Luwu", url: "https://spse.inaproc.id/luwu/eproc4" },
  { nama: "LPSE Kabupaten Luwu Utara", url: "https://spse.inaproc.id/luwuutara/eproc4" },
  { nama: "LPSE Kabupaten Luwu Timur", url: "https://spse.inaproc.id/luwutimur/eproc4" },
  { nama: "LPSE Kabupaten Toraja Utara", url: "https://spse.inaproc.id/torajautara/eproc4" },
  { nama: "LPSE Kabupaten Tana Toraja", url: "https://spse.inaproc.id/tanatoraja/eproc4" },

  // ── SULAWESI TENGAH ───────────────────────────────────────────────────
  { nama: "LPSE Provinsi Sulawesi Tengah", url: "https://spse.inaproc.id/sultengprov/eproc4" },
  { nama: "LPSE Kota Palu", url: "https://spse.inaproc.id/palu/eproc4" },
  { nama: "LPSE Kabupaten Donggala", url: "https://spse.inaproc.id/donggala/eproc4" },
  { nama: "LPSE Kabupaten Sigi", url: "https://spse.inaproc.id/sigi/eproc4" },
  { nama: "LPSE Kabupaten Poso", url: "https://spse.inaproc.id/poso/eproc4" },
  { nama: "LPSE Kabupaten Morowali", url: "https://spse.inaproc.id/morowali/eproc4" },
  { nama: "LPSE Kabupaten Tolitoli", url: "https://spse.inaproc.id/tolitoli/eproc4" },
  { nama: "LPSE Kabupaten Buol", url: "https://spse.inaproc.id/buol/eproc4" },
  { nama: "LPSE Kabupaten Banggai", url: "https://spse.inaproc.id/banggai/eproc4" },
  { nama: "LPSE Kabupaten Parigi Moutong", url: "https://spse.inaproc.id/parigimo/eproc4" },

  // ── SULAWESI UTARA ────────────────────────────────────────────────────
  { nama: "LPSE Provinsi Sulawesi Utara", url: "https://spse.inaproc.id/sulutprov/eproc4" },
  { nama: "LPSE Kota Manado", url: "https://spse.inaproc.id/manado/eproc4" },
  { nama: "LPSE Kota Bitung", url: "https://spse.inaproc.id/bitung/eproc4" },
  { nama: "LPSE Kota Tomohon", url: "https://spse.inaproc.id/tomohon/eproc4" },
  { nama: "LPSE Kota Kotamobagu", url: "https://spse.inaproc.id/kotamobagu/eproc4" },
  { nama: "LPSE Kabupaten Minahasa", url: "https://spse.inaproc.id/minahasa/eproc4" },
  { nama: "LPSE Kabupaten Minahasa Utara", url: "https://spse.inaproc.id/minahasautara/eproc4" },
  { nama: "LPSE Kabupaten Minahasa Selatan", url: "https://spse.inaproc.id/minahasasel/eproc4" },
  { nama: "LPSE Kabupaten Bolaang Mongondow", url: "https://spse.inaproc.id/bolmong/eproc4" },
  { nama: "LPSE Kabupaten Kepulauan Sangihe", url: "https://spse.inaproc.id/sangihe/eproc4" },
  { nama: "LPSE Kabupaten Kepulauan Talaud", url: "https://spse.inaproc.id/talaud/eproc4" },

  // ── SULAWESI TENGGARA ─────────────────────────────────────────────────
  { nama: "LPSE Provinsi Sulawesi Tenggara", url: "https://spse.inaproc.id/sultraprov/eproc4" },
  { nama: "LPSE Kota Kendari", url: "https://spse.inaproc.id/kendari/eproc4" },
  { nama: "LPSE Kota Baubau", url: "https://spse.inaproc.id/baubau/eproc4" },
  { nama: "LPSE Kabupaten Konawe", url: "https://spse.inaproc.id/konawe/eproc4" },
  { nama: "LPSE Kabupaten Konawe Selatan", url: "https://spse.inaproc.id/konsel/eproc4" },
  { nama: "LPSE Kabupaten Kolaka", url: "https://spse.inaproc.id/kolaka/eproc4" },
  { nama: "LPSE Kabupaten Kolaka Utara", url: "https://spse.inaproc.id/kolakautara/eproc4" },
  { nama: "LPSE Kabupaten Muna", url: "https://spse.inaproc.id/muna/eproc4" },
  { nama: "LPSE Kabupaten Buton", url: "https://spse.inaproc.id/buton/eproc4" },
  { nama: "LPSE Kabupaten Bombana", url: "https://spse.inaproc.id/bombana/eproc4" },
  { nama: "LPSE Kabupaten Wakatobi", url: "https://spse.inaproc.id/wakatobi/eproc4" },

  // ── GORONTALO ─────────────────────────────────────────────────────────
  { nama: "LPSE Provinsi Gorontalo", url: "https://spse.inaproc.id/gorontaloprov/eproc4" },
  { nama: "LPSE Kota Gorontalo", url: "https://spse.inaproc.id/gorontalokota/eproc4" },
  { nama: "LPSE Kabupaten Gorontalo", url: "https://spse.inaproc.id/gorontalokab/eproc4" },
  { nama: "LPSE Kabupaten Gorontalo Utara", url: "https://spse.inaproc.id/gorut/eproc4" },
  { nama: "LPSE Kabupaten Bone Bolango", url: "https://spse.inaproc.id/bonebol/eproc4" },
  { nama: "LPSE Kabupaten Pohuwato", url: "https://spse.inaproc.id/pohuwato/eproc4" },
  { nama: "LPSE Kabupaten Boalemo", url: "https://spse.inaproc.id/boalemo/eproc4" },

  // ── SULAWESI BARAT ────────────────────────────────────────────────────
  { nama: "LPSE Provinsi Sulawesi Barat", url: "https://spse.inaproc.id/sulbarprov/eproc4" },
  { nama: "LPSE Kabupaten Mamuju", url: "https://spse.inaproc.id/mamuju/eproc4" },
  { nama: "LPSE Kabupaten Majene", url: "https://spse.inaproc.id/majene/eproc4" },
  { nama: "LPSE Kabupaten Polewali Mandar", url: "https://spse.inaproc.id/polman/eproc4" },
  { nama: "LPSE Kabupaten Mamasa", url: "https://spse.inaproc.id/mamasa/eproc4" },

  // ── BALI ─────────────────────────────────────────────────────────────
  { nama: "LPSE Provinsi Bali", url: "https://spse.inaproc.id/baliprov/eproc4" },
  { nama: "LPSE Kota Denpasar", url: "https://spse.inaproc.id/denpasar/eproc4" },
  { nama: "LPSE Kabupaten Badung", url: "https://spse.inaproc.id/badung/eproc4" },
  { nama: "LPSE Kabupaten Gianyar", url: "https://spse.inaproc.id/gianyar/eproc4" },
  { nama: "LPSE Kabupaten Tabanan", url: "https://spse.inaproc.id/tabanan/eproc4" },
  { nama: "LPSE Kabupaten Buleleng", url: "https://spse.inaproc.id/buleleng/eproc4" },
  { nama: "LPSE Kabupaten Jembrana", url: "https://spse.inaproc.id/jembrana/eproc4" },
  { nama: "LPSE Kabupaten Klungkung", url: "https://spse.inaproc.id/klungkung/eproc4" },
  { nama: "LPSE Kabupaten Bangli", url: "https://spse.inaproc.id/bangli/eproc4" },
  { nama: "LPSE Kabupaten Karangasem", url: "https://spse.inaproc.id/karangasem/eproc4" },

  // ── NUSA TENGGARA BARAT ───────────────────────────────────────────────
  { nama: "LPSE Provinsi NTB", url: "https://spse.inaproc.id/ntbprov/eproc4" },
  { nama: "LPSE Kota Mataram", url: "https://spse.inaproc.id/mataram/eproc4" },
  { nama: "LPSE Kota Bima", url: "https://spse.inaproc.id/bimakota/eproc4" },
  { nama: "LPSE Kabupaten Lombok Barat", url: "https://spse.inaproc.id/lombokbarat/eproc4" },
  { nama: "LPSE Kabupaten Lombok Tengah", url: "https://spse.inaproc.id/lomboktengah/eproc4" },
  { nama: "LPSE Kabupaten Lombok Timur", url: "https://spse.inaproc.id/lomboktimur/eproc4" },
  { nama: "LPSE Kabupaten Lombok Utara", url: "https://spse.inaproc.id/lombokutara/eproc4" },
  { nama: "LPSE Kabupaten Sumbawa", url: "https://spse.inaproc.id/sumbawa/eproc4" },
  { nama: "LPSE Kabupaten Sumbawa Barat", url: "https://spse.inaproc.id/sumbawabarat/eproc4" },
  { nama: "LPSE Kabupaten Dompu", url: "https://spse.inaproc.id/dompu/eproc4" },
  { nama: "LPSE Kabupaten Bima", url: "https://spse.inaproc.id/bimakab/eproc4" },

  // ── NUSA TENGGARA TIMUR ───────────────────────────────────────────────
  { nama: "LPSE Provinsi NTT", url: "https://spse.inaproc.id/nttprov/eproc4" },
  { nama: "LPSE Kota Kupang", url: "https://spse.inaproc.id/kupangkota/eproc4" },
  { nama: "LPSE Kabupaten Kupang", url: "https://spse.inaproc.id/kupangkab/eproc4" },
  { nama: "LPSE Kabupaten Timor Tengah Utara", url: "https://spse.inaproc.id/ttu/eproc4" },
  { nama: "LPSE Kabupaten Timor Tengah Selatan", url: "https://spse.inaproc.id/tts/eproc4" },
  { nama: "LPSE Kabupaten Belu", url: "https://spse.inaproc.id/belu/eproc4" },
  { nama: "LPSE Kabupaten Ende", url: "https://spse.inaproc.id/ende/eproc4" },
  { nama: "LPSE Kabupaten Flores Timur", url: "https://spse.inaproc.id/flotim/eproc4" },
  { nama: "LPSE Kabupaten Sikka", url: "https://spse.inaproc.id/sikka/eproc4" },
  { nama: "LPSE Kabupaten Manggarai", url: "https://spse.inaproc.id/manggarai/eproc4" },
  { nama: "LPSE Kabupaten Manggarai Barat", url: "https://spse.inaproc.id/manggaraibarat/eproc4" },
  { nama: "LPSE Kabupaten Manggarai Timur", url: "https://spse.inaproc.id/manggaraitimur/eproc4" },
  { nama: "LPSE Kabupaten Sumba Barat", url: "https://spse.inaproc.id/sumbabarat/eproc4" },
  { nama: "LPSE Kabupaten Sumba Timur", url: "https://spse.inaproc.id/sumbatimur/eproc4" },

  // ── MALUKU ────────────────────────────────────────────────────────────
  { nama: "LPSE Provinsi Maluku", url: "https://spse.inaproc.id/malukuprov/eproc4" },
  { nama: "LPSE Kota Ambon", url: "https://spse.inaproc.id/ambon/eproc4" },
  { nama: "LPSE Kota Tual", url: "https://spse.inaproc.id/tual/eproc4" },
  { nama: "LPSE Kabupaten Maluku Tengah", url: "https://spse.inaproc.id/maltengah/eproc4" },
  { nama: "LPSE Kabupaten Seram Bagian Barat", url: "https://spse.inaproc.id/sbb/eproc4" },
  { nama: "LPSE Kabupaten Seram Bagian Timur", url: "https://spse.inaproc.id/sbt/eproc4" },
  { nama: "LPSE Kabupaten Maluku Tenggara", url: "https://spse.inaproc.id/maltenggara/eproc4" },
  { nama: "LPSE Kabupaten Buru", url: "https://spse.inaproc.id/buru/eproc4" },

  // ── MALUKU UTARA ──────────────────────────────────────────────────────
  { nama: "LPSE Provinsi Maluku Utara", url: "https://spse.inaproc.id/malutprov/eproc4" },
  { nama: "LPSE Kota Ternate", url: "https://spse.inaproc.id/ternate/eproc4" },
  { nama: "LPSE Kota Tidore Kepulauan", url: "https://spse.inaproc.id/tidorekepulauan/eproc4" },
  { nama: "LPSE Kabupaten Halmahera Barat", url: "https://spse.inaproc.id/halbar/eproc4" },
  { nama: "LPSE Kabupaten Halmahera Tengah", url: "https://spse.inaproc.id/haltengah/eproc4" },
  { nama: "LPSE Kabupaten Halmahera Utara", url: "https://spse.inaproc.id/halut/eproc4" },
  { nama: "LPSE Kabupaten Halmahera Selatan", url: "https://spse.inaproc.id/halsel/eproc4" },
  { nama: "LPSE Kabupaten Kepulauan Sula", url: "https://spse.inaproc.id/sula/eproc4" },

  // ── PAPUA ─────────────────────────────────────────────────────────────
  { nama: "LPSE Provinsi Papua", url: "https://spse.inaproc.id/papuaprov/eproc4" },
  { nama: "LPSE Kota Jayapura", url: "https://spse.inaproc.id/jayapurakota/eproc4" },
  { nama: "LPSE Kabupaten Jayapura", url: "https://spse.inaproc.id/jayapurakab/eproc4" },
  { nama: "LPSE Kabupaten Merauke", url: "https://spse.inaproc.id/merauke/eproc4" },
  { nama: "LPSE Kabupaten Biak Numfor", url: "https://spse.inaproc.id/biak/eproc4" },
  { nama: "LPSE Kabupaten Sorong", url: "https://spse.inaproc.id/sorongkab/eproc4" },
  { nama: "LPSE Kabupaten Mimika", url: "https://spse.inaproc.id/mimika/eproc4" },
  { nama: "LPSE Kabupaten Nabire", url: "https://spse.inaproc.id/nabire/eproc4" },
  { nama: "LPSE Kabupaten Pegunungan Bintang", url: "https://spse.inaproc.id/pegbinatang/eproc4" },
  { nama: "LPSE Kabupaten Yahukimo", url: "https://spse.inaproc.id/yahukimo/eproc4" },

  // ── PAPUA BARAT ───────────────────────────────────────────────────────
  { nama: "LPSE Provinsi Papua Barat", url: "https://spse.inaproc.id/papuabaratprov/eproc4" },
  { nama: "LPSE Kota Sorong", url: "https://spse.inaproc.id/sorongkota/eproc4" },
  { nama: "LPSE Kabupaten Manokwari", url: "https://spse.inaproc.id/manokwari/eproc4" },
  { nama: "LPSE Kabupaten Raja Ampat", url: "https://spse.inaproc.id/rajaampat/eproc4" },
  { nama: "LPSE Kabupaten Fak Fak", url: "https://spse.inaproc.id/fakfak/eproc4" },
  { nama: "LPSE Kabupaten Kaimana", url: "https://spse.inaproc.id/kaimana/eproc4" },
  { nama: "LPSE Kabupaten Teluk Bintuni", url: "https://spse.inaproc.id/telukbintuni/eproc4" },
  { nama: "LPSE Kabupaten Teluk Wondama", url: "https://spse.inaproc.id/telukwondama/eproc4" },

  // ── ACEH ─────────────────────────────────────────────────────────────
  { nama: "LPSE Provinsi Aceh", url: "https://spse.inaproc.id/acehprov/eproc4" },
  { nama: "LPSE Kota Banda Aceh", url: "https://spse.inaproc.id/bandaaceh/eproc4" },
  { nama: "LPSE Kota Sabang", url: "https://spse.inaproc.id/sabang/eproc4" },
  { nama: "LPSE Kota Lhokseumawe", url: "https://spse.inaproc.id/lhokseumawe/eproc4" },
  { nama: "LPSE Kota Langsa", url: "https://spse.inaproc.id/langsa/eproc4" },
  { nama: "LPSE Kota Subulussalam", url: "https://spse.inaproc.id/subulussalam/eproc4" },
  { nama: "LPSE Kabupaten Aceh Besar", url: "https://spse.inaproc.id/acehbesar/eproc4" },
  { nama: "LPSE Kabupaten Pidie", url: "https://spse.inaproc.id/pidie/eproc4" },
  { nama: "LPSE Kabupaten Bireuen", url: "https://spse.inaproc.id/bireuen/eproc4" },
  { nama: "LPSE Kabupaten Aceh Utara", url: "https://spse.inaproc.id/acehu/eproc4" },
  { nama: "LPSE Kabupaten Aceh Timur", url: "https://spse.inaproc.id/acehtimur/eproc4" },
  { nama: "LPSE Kabupaten Aceh Barat", url: "https://spse.inaproc.id/acehbarat/eproc4" },
  { nama: "LPSE Kabupaten Aceh Selatan", url: "https://spse.inaproc.id/acehselatan/eproc4" },
  { nama: "LPSE Kabupaten Aceh Tenggara", url: "https://spse.inaproc.id/acehtenggara/eproc4" },
  { nama: "LPSE Kabupaten Aceh Singkil", url: "https://spse.inaproc.id/acehsingkil/eproc4" },
  { nama: "LPSE Kabupaten Aceh Tamiang", url: "https://spse.inaproc.id/acehtamiang/eproc4" },
  { nama: "LPSE Kabupaten Nagan Raya", url: "https://spse.inaproc.id/naganraya/eproc4" },
  { nama: "LPSE Kabupaten Gayo Lues", url: "https://spse.inaproc.id/gayolues/eproc4" },

  // ── IKN (IBUKATA NEGARA) ──────────────────────────────────────────────
  { nama: "LPSE Otorita IKN", url: "https://spse.inaproc.id/ikn/eproc4" },
];

module.exports = { LPSE_LIST };
